jdk:
- oraclejdk8
language: java
notification:
  email:
    on_failure: always
    recipients:
    - dev@kylin.apache.org
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn test -B
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
